pull_request_rules:
  - name: auto merge with templated commit message
    conditions:
      - base=main
    actions:
      merge:
        method: merge
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
